### ISSUE TITLE
Install.sh script could also have an update option

### ISSUE THREAD

**Issue by bcelary** [CryptoMF/frostybot#2]
Hi CryptoMF!

Just updating the bot to use the latest comment FR and thought that the install.sh script could do git pull if the repo has been previously cloned. I would provide you with a patch but it looks that this script is not part of the repo.

EDIT: Realized you've got a check if the install dir exists in the script. I've added a git pull command in there but first I had to move aside the config file and restore it when the repo is updated as it causes merge conflict during pull.

Cheers,
SemiQuasi

**Comment by CryptoMF** [comment]
Hey man, thanks for reaching out. Yeah, I specifically didn't want the install.sh script to be in the repo because I'm not entirely happy with it. I'm thinking I'm gonna rather opt for a containerized/hosted approach, because even with an install script a lot of guys are battling. I sometime take for granted that people know how to use Linux or Git, but most of the guys using this software have never logged into Linux before, so I need to make this a LOT more easier than just an install script.

**Comment by CryptoMF** [comment]
Having said all that, the install.sh script already detects existing frostybot installations, so it really wouldn't be too hard to make it update as well.

**Comment by bcelary** [comment]
💯 - exactly what I've done - found that it detects that and made a minor change to update it from git for now.

I agree it is much better to do a different take on the installation/update. Good point!
