### ISSUE TITLE
How do you protect from possible TradingView spam?

### ISSUE THREAD

**Issue by JDJoe** [CryptoMF/frostybot#5]
Maybe I missed something but there is absolutely no way to be sure if order was sent to my bot from me on any random user on TradingView who discovered my bot's URL? 
Not even a simple "PIN" or what ever string to be used for verification of a webhook message?

**Comment by CryptoMF** [comment]
Hi! Thanks for the question. Yes, there is built-in protection. By default, Frostybot will only allow URL requests from addresses in it's "whitelist". The 4 known TradingView webhook addresses are in the whitelist by default. You can use the following command to view the whitelist:

`./frostybot whitelist`

If you would like to allow any other addresses to talk to your bot, you can add them with the following command:

`./frostybot whitelist add="<ip address>" description="<your own description>"`

To remove an address from the whitelist, use this command:

`./frostybot whitelist remove="<ip address>"`

Note that it will **not** allow you to remove the 4 preconfigured Tradingview addresses. You can test that your bot is protected by putting your webhook address into your browser. You should see an error stating that your address is not authorised.

**Comment by CryptoMF** [comment]
My apologies, I miss-read your question, so I reopened the issue. 

The short answer is no. If I had your webhook URL I could send commands to your bot. The webhook URL in the Tradingview alert is just as secure as the content of the message box where you enter the commands. Having a pin would not really make it any more secure, since both the webhook URL and the message box contents are equally accessible. My suggestion would be to keep your webhook URL confidential.

If you have another suggestion to try and make it more secure, I'd be happy to implement it for you.

**Comment by CryptoMF** [comment]
@arnoudb has proposed a pin=xxxx parameter for exchange commands, which I think is what you meant. We'll add it in the next few days as an optional way to make it more secure. 

So we'll add this command for updating the pin

`./frostybot pin oldpin="<youroldpin>" newpin="newpin" `

And then you just add the pin to your exchange commands:

`./frostybot <stub>:long size=2x symbol=BTCUSD pin=xxxx`

**Comment by bcelary** [comment]
I think this really does not add too much value and the functionality is already there: use a confidential URL in your web server.

**Comment by CryptoMF** [comment]
One could get the same affect as a pin my obfuscating your account stub. For example, instead of _deribit_, call it _rfckjnw_. When executing command, you would do this instead:

`rfckjnw:long size=200 symbol=BTCUSD`

This would have exactly the same security effect as adding the pin=xxxx parameter as proposed.

**Comment by JDJoe** [comment]
Thanks. Maybe something to add to doc's. :)
